---
# tasks file for ansible-role-docker

- name: Converge ansible_machine
  set_fact:
    converged_machine: amd64
  when: 'ansible_machine == "x86_64"'

- name: Converge ansible_machine
  set_fact:
    converged_machine: arm64
  when: 'ansible_machine == "aarch64"'

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
  
- name: Add an apt signing key for Docker
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "deb [arch={{ converged_machine }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli 
    - containerd.io

- name: Add user to docker group
  user:
    name: "{{ item }}"
    group: docker
  loop: "{{ docker_users }}"

- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_machine }}"
    dest: ~/docker-compose
    mode: '+x'
  
- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists